version: "3.8"

networks:
    backend:
        driver: ${NETWORKS_DRIVER}

services:
    httpd:
        image: php-docker-docaposte/httpd
        build:
            context: .
            dockerfile: ./httpd/Dockerfile
            args:
                - TZ=${TIMEZONE}
        container_name: httpd
        volumes:
            - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
        ports:
            - "${APACHE_HOST_HTTP_PORT}:80"
            - "${APACHE_HOST_HTTPS_PORT}:443"
        networks:
            backend:
                aliases:
                    - ${APP_HOST}

    phpfpm-8.1:
        image: php-docker-docaposte/php-fpm-8.1
        build:
            context: .
            dockerfile: ./php-fpm/8.1/Dockerfile
            args:
                - TARGET_PHP_VERSION=${PHP_VERSION}
                - TZ=${TIMEZONE}
        container_name: php-fpm-8.1
        ports:
            - 5173:5173
        volumes:
            - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
        networks:
            - backend

    db:
        image: mariadb:10.2
        container_name: mariadb
        volumes:
            - mysql-data:/var/lib/mysql
            - ./mariadb/dump:/docker-entrypoint-initdb.d
        ports:
            - "3308:3306"
        environment:
            MYSQL_DATABASE: DOCKER
            MYSQL_ROOT_PASSWORD: sqlsql
            TZ: Europe/Paris
        networks:
            - backend

volumes:
    mysql-data:
